import json
import time
import urllib.parse
import urllib.request
import sys
import os

try:
    sys.stdout.reconfigure(encoding='utf-8')
except AttributeError:
    pass

INPUT_FILE = "dictation_data.json"
TEMP_FILE = "dictation_data_temp.json"
OUTPUT_FILE = "dictation_data.json"

def translate_vi_to_zh(text):
    try:
        url = "https://translate.googleapis.com/translate_a/single?client=gtx&sl=vi&tl=zh-CN&dt=t&q=" + urllib.parse.quote(text)
        req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
        with urllib.request.urlopen(req, timeout=10) as response:
            data = json.loads(response.read().decode('utf-8'))
            if data and data[0] and data[0][0]:
                res = data[0][0][0].strip()
                # Strip full stop if needed, or keep it
                return res
    except Exception as e:
        print(f"\nError translating '{text}': {e}")
    return None

def main():
    if os.path.exists(TEMP_FILE):
        print(f"Resuming translation from {TEMP_FILE}...")
        with open(TEMP_FILE, "r", encoding="utf-8") as f:
            all_data = json.load(f)
    else:
        print(f"Loading {INPUT_FILE}...")
        with open(INPUT_FILE, "r", encoding="utf-8") as f:
            all_data = json.load(f)

    total_translated = 0
    total_to_translate = 0
    
    # Count total to translate
    for sheet, items in all_data.items():
        for item in items:
            if item.get("zh") == "???":
                total_to_translate += 1

    print(f"Total locked sentences to translate: {total_to_translate}")
    if total_to_translate == 0:
        print("No sentences need translation!")
        return

    count = 0
    start_time = time.time()
    
    try:
        for sheet, items in all_data.items():
            for item in items:
                if item.get("zh") == "???":
                    vi_text = item.get("vi", "")
                    if not vi_text:
                        continue
                        
                    # Translate
                    zh_translated = translate_vi_to_zh(vi_text)
                    if zh_translated:
                        item["zh"] = zh_translated
                        item["pinyin"] = "..."  # Will be dynamically generated by browser
                        total_translated += 1
                    
                    count += 1
                    # Print progress
                    sys.stdout.write(f"\rProgress: {count}/{total_to_translate} (Translated: {total_translated})")
                    sys.stdout.flush()
                    
                    # Sleep to prevent rate limit
                    time.sleep(0.3)
                    
                    # Periodic save to temp file every 50 translations
                    if count % 50 == 0:
                        with open(TEMP_FILE, "w", encoding="utf-8") as f:
                            json.dump(all_data, f, ensure_ascii=False, indent=2)
                            
    except KeyboardInterrupt:
        print("\nTranslation paused by user. Saving progress...")
        with open(TEMP_FILE, "w", encoding="utf-8") as f:
            json.dump(all_data, f, ensure_ascii=False, indent=2)
        print("Progress saved. You can rerun the script to resume.")
        return

    # Done! Save to final file and clean temp file
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(all_data, f, ensure_ascii=False, indent=2)
    
    if os.path.exists(TEMP_FILE):
        os.remove(TEMP_FILE)
        
    print(f"\nSUCCESS: Translated {total_translated} sentences in {time.time() - start_time:.1f} seconds.")

if __name__ == "__main__":
    main()
